# This is a basic workflow to help you get started with Actions

name: Flujo Reutilizable

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
        
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          username: ${{ inputs.username }}

      - name: Run a multi-line script
        run: |
          echo Soy el usuario username
